export const REQUEST_GET_COMPANYSIZES = 'REQUEST_GET_COMPANYSIZES';
export const RECEIVE_GET_COMPANYSIZES = 'RECEIVE_GET_COMPANYSIZES';
export const ERROR_GET_COMPANYSIZES = 'ERROR_GET_COMPANYSIZES';

export const REQUEST_GET_COMPANYSIZE = 'REQUEST_GET_COMPANYSIZE';
export const RECEIVE_GET_COMPANYSIZE = 'RECEIVE_GET_COMPANYSIZE';
export const ERROR_GET_COMPANYSIZE = 'ERROR_GET_COMPANYSIZE';

export const REQUEST_ADD_NEW_COMPANYSIZE = 'REQUEST_ADD_NEW_COMPANYSIZE';
export const RECEIVE_ADD_NEW_COMPANYSIZE = 'RECEIVE_ADD_NEW_COMPANYSIZE';
export const ERROR_ADD_NEW_COMPANYSIZE = 'ERROR_ADD_NEW_COMPANYSIZE';

export const REQUEST_EDIT_COMPANYSIZE = 'REQUEST_EDIT_COMPANYSIZE';
export const RECEIVE_EDIT_COMPANYSIZE = 'RECEIVE_EDIT_COMPANYSIZE';
export const ERROR_EDIT_COMPANYSIZE = 'ERROR_EDIT_COMPANYSIZE';

export const REQUEST_REMOVE_COMPANYSIZE = 'REQUEST_REMOVE_COMPANYSIZE';
export const RECEIVE_REMOVE_COMPANYSIZE = 'RECEIVE_REMOVE_COMPANYSIZE';
export const ERROR_REMOVE_COMPANYSIZE = 'ERROR_REMOVE_COMPANYSIZE';

export const TOGGLE_LOADING_COMPANYSIZES = 'TOGGLE_LOADING_COMPANYSIZES';

export const TOGGLE_SNACKBAR_COMPANYSIZES = 'TOGGLE_SNACKBAR_COMPANYSIZES';
export const TOGGLE_DELETE_COMPANYSIZE_MODAL = 'TOGGLE_DELETE_COMPANYSIZE_MODAL';
