export const REQUEST_GET_SEARCHS = 'REQUEST_GET_SEARCHS';
export const RECEIVE_GET_SEARCHS = 'RECEIVE_GET_SEARCHS';
export const ERROR_GET_SEARCHS = 'ERROR_GET_SEARCHS';

export const REQUEST_GET_SEARCH = 'REQUEST_GET_SEARCH';
export const RECEIVE_GET_SEARCH = 'RECEIVE_GET_SEARCH';
export const ERROR_GET_SEARCH = 'ERROR_GET_SEARCH';

export const REQUEST_ADD_NEW_SEARCH = 'REQUEST_ADD_NEW_SEARCH';
export const RECEIVE_ADD_NEW_SEARCH = 'RECEIVE_ADD_NEW_SEARCH';
export const ERROR_ADD_NEW_SEARCH = 'ERROR_ADD_NEW_SEARCH';

export const REQUEST_EDIT_SEARCH = 'REQUEST_EDIT_SEARCH';
export const RECEIVE_EDIT_SEARCH = 'RECEIVE_EDIT_SEARCH';
export const ERROR_EDIT_SEARCH = 'ERROR_EDIT_SEARCH';

export const REQUEST_REMOVE_SEARCH = 'REQUEST_REMOVE_SEARCH';
export const RECEIVE_REMOVE_SEARCH = 'RECEIVE_REMOVE_SEARCH';
export const ERROR_REMOVE_SEARCH = 'ERROR_REMOVE_SEARCH';

export const TOGGLE_LOADING_SEARCHS = 'TOGGLE_LOADING_SEARCHS';

export const TOGGLE_SNACKBAR_SEARCHS = 'TOGGLE_SNACKBAR_SEARCHS';
export const TOGGLE_DELETE_SEARCH_MODAL = 'TOGGLE_DELETE_SEARCH_MODAL';
