export const REQUEST_GET_TECHSKILLS = 'REQUEST_GET_TECHSKILLS';
export const RECEIVE_GET_TECHSKILLS = 'RECEIVE_GET_TECHSKILLS';
export const ERROR_GET_TECHSKILLS = 'ERROR_GET_TECHSKILLS';

export const REQUEST_GET_TECHSKILL = 'REQUEST_GET_TECHSKILL';
export const RECEIVE_GET_TECHSKILL = 'RECEIVE_GET_TECHSKILL';
export const ERROR_GET_TECHSKILL = 'ERROR_GET_TECHSKILL';

export const REQUEST_ADD_NEW_TECHSKILL = 'REQUEST_ADD_NEW_TECHSKILL';
export const RECEIVE_ADD_NEW_TECHSKILL = 'RECEIVE_ADD_NEW_TECHSKILL';
export const ERROR_ADD_NEW_TECHSKILL = 'ERROR_ADD_NEW_TECHSKILL';

export const REQUEST_EDIT_TECHSKILL = 'REQUEST_EDIT_TECHSKILL';
export const RECEIVE_EDIT_TECHSKILL = 'RECEIVE_EDIT_TECHSKILL';
export const ERROR_EDIT_TECHSKILL = 'ERROR_EDIT_TECHSKILL';

export const REQUEST_REMOVE_TECHSKILL = 'REQUEST_REMOVE_TECHSKILL';
export const RECEIVE_REMOVE_TECHSKILL = 'RECEIVE_REMOVE_TECHSKILL';
export const ERROR_REMOVE_TECHSKILL = 'ERROR_REMOVE_TECHSKILL';

export const TOGGLE_LOADING_TECHSKILLS = 'TOGGLE_LOADING_TECHSKILLS';

export const TOGGLE_SNACKBAR_TECHSKILLS = 'TOGGLE_SNACKBAR_TECHSKILLS';
export const TOGGLE_DELETE_TECHSKILL_MODAL = 'TOGGLE_DELETE_TECHSKILL_MODAL';
