export const REQUEST_GET_AREAS = 'REQUEST_GET_AREAS';
export const RECEIVE_GET_AREAS = 'RECEIVE_GET_AREAS';
export const ERROR_GET_AREAS = 'ERROR_GET_AREAS';

export const REQUEST_GET_AREA = 'REQUEST_GET_AREA';
export const RECEIVE_GET_AREA = 'RECEIVE_GET_AREA';
export const ERROR_GET_AREA = 'ERROR_GET_AREA';

export const REQUEST_ADD_NEW_AREA = 'REQUEST_ADD_NEW_AREA';
export const RECEIVE_ADD_NEW_AREA = 'RECEIVE_ADD_NEW_AREA';
export const ERROR_ADD_NEW_AREA = 'ERROR_ADD_NEW_AREA';

export const REQUEST_EDIT_AREA = 'REQUEST_EDIT_AREA';
export const RECEIVE_EDIT_AREA = 'RECEIVE_EDIT_AREA';
export const ERROR_EDIT_AREA = 'ERROR_EDIT_AREA';

export const REQUEST_REMOVE_AREA = 'REQUEST_REMOVE_AREA';
export const RECEIVE_REMOVE_AREA = 'RECEIVE_REMOVE_AREA';
export const ERROR_REMOVE_AREA = 'ERROR_REMOVE_AREA';

export const TOGGLE_LOADING_AREAS = 'TOGGLE_LOADING_AREAS';

export const TOGGLE_SNACKBAR_AREAS = 'TOGGLE_SNACKBAR_AREAS';
export const TOGGLE_DELETE_AREA_MODAL = 'TOGGLE_DELETE_AREA_MODAL';
