export const REQUEST_GET_CLIENTS = 'REQUEST_GET_CLIENTS';
export const RECEIVE_GET_CLIENTS = 'RECEIVE_GET_CLIENTS';
export const ERROR_GET_CLIENTS = 'ERROR_GET_CLIENTS';

export const REQUEST_GET_CLIENT = 'REQUEST_GET_CLIENT';
export const RECEIVE_GET_CLIENT = 'RECEIVE_GET_CLIENT';
export const ERROR_GET_CLIENT = 'ERROR_GET_CLIENT';

export const REQUEST_ADD_NEW_CLIENT = 'REQUEST_ADD_NEW_CLIENT';
export const RECEIVE_ADD_NEW_CLIENT = 'RECEIVE_ADD_NEW_CLIENT';
export const ERROR_ADD_NEW_CLIENT = 'ERROR_ADD_NEW_CLIENT';

export const REQUEST_EDIT_CLIENT = 'REQUEST_EDIT_CLIENT';
export const RECEIVE_EDIT_CLIENT = 'RECEIVE_EDIT_CLIENT';
export const ERROR_EDIT_CLIENT = 'ERROR_EDIT_CLIENT';

export const REQUEST_REMOVE_CLIENT = 'REQUEST_REMOVE_CLIENT';
export const RECEIVE_REMOVE_CLIENT = 'RECEIVE_REMOVE_CLIENT';
export const ERROR_REMOVE_CLIENT = 'ERROR_REMOVE_CLIENT';

export const TOGGLE_LOADING_CLIENTS = 'TOGGLE_LOADING_CLIENTS';

export const TOGGLE_SNACKBAR_CLIENTS = 'TOGGLE_SNACKBAR_CLIENTS';
export const TOGGLE_DELETE_CLIENT_MODAL = 'TOGGLE_DELETE_CLIENT_MODAL';
