export const REQUEST_GET_SECTORS = 'REQUEST_GET_SECTORS';
export const RECEIVE_GET_SECTORS = 'RECEIVE_GET_SECTORS';
export const ERROR_GET_SECTORS = 'ERROR_GET_SECTORS';

export const REQUEST_GET_SECTOR = 'REQUEST_GET_SECTOR';
export const RECEIVE_GET_SECTOR = 'RECEIVE_GET_SECTOR';
export const ERROR_GET_SECTOR = 'ERROR_GET_SECTOR';

export const REQUEST_ADD_NEW_SECTOR = 'REQUEST_ADD_NEW_SECTOR';
export const RECEIVE_ADD_NEW_SECTOR = 'RECEIVE_ADD_NEW_SECTOR';
export const ERROR_ADD_NEW_SECTOR = 'ERROR_ADD_NEW_SECTOR';

export const REQUEST_EDIT_SECTOR = 'REQUEST_EDIT_SECTOR';
export const RECEIVE_EDIT_SECTOR = 'RECEIVE_EDIT_SECTOR';
export const ERROR_EDIT_SECTOR = 'ERROR_EDIT_SECTOR';

export const REQUEST_REMOVE_SECTOR = 'REQUEST_REMOVE_SECTOR';
export const RECEIVE_REMOVE_SECTOR = 'RECEIVE_REMOVE_SECTOR';
export const ERROR_REMOVE_SECTOR = 'ERROR_REMOVE_SECTOR';

export const TOGGLE_LOADING_SECTORS = 'TOGGLE_LOADING_SECTORS';

export const TOGGLE_SNACKBAR_SECTORS = 'TOGGLE_SNACKBAR_SECTORS';
export const TOGGLE_DELETE_SECTOR_MODAL = 'TOGGLE_DELETE_SECTOR_MODAL';
