export const REQUEST_GET_COUNTRIES = 'REQUEST_GET_COUNTRIES';
export const RECEIVE_GET_COUNTRIES = 'RECEIVE_GET_COUNTRIES';
export const ERROR_GET_COUNTRIES = 'ERROR_GET_COUNTRIES';

export const REQUEST_GET_COUNTRY = 'REQUEST_GET_COUNTRY';
export const RECEIVE_GET_COUNTRY = 'RECEIVE_GET_COUNTRY';
export const ERROR_GET_COUNTRY = 'ERROR_GET_COUNTRY';

export const REQUEST_ADD_NEW_COUNTRY = 'REQUEST_ADD_NEW_COUNTRY';
export const RECEIVE_ADD_NEW_COUNTRY = 'RECEIVE_ADD_NEW_COUNTRY';
export const ERROR_ADD_NEW_COUNTRY = 'ERROR_ADD_NEW_COUNTRY';

export const REQUEST_EDIT_COUNTRY = 'REQUEST_EDIT_COUNTRY';
export const RECEIVE_EDIT_COUNTRY = 'RECEIVE_EDIT_COUNTRY';
export const ERROR_EDIT_COUNTRY = 'ERROR_EDIT_COUNTRY';

export const REQUEST_REMOVE_COUNTRY = 'REQUEST_REMOVE_COUNTRY';
export const RECEIVE_REMOVE_COUNTRY = 'RECEIVE_REMOVE_COUNTRY';
export const ERROR_REMOVE_COUNTRY = 'ERROR_REMOVE_COUNTRY';

export const TOGGLE_LOADING_COUNTRIES = 'TOGGLE_LOADING_COUNTRIES';

export const TOGGLE_SNACKBAR_COUNTRIES = 'TOGGLE_SNACKBAR_COUNTRIES';
export const TOGGLE_DELETE_COUNTRY_MODAL = 'TOGGLE_DELETE_COUNTRY_MODAL';
