export const REQUEST_GET_SOFTSKILLS = 'REQUEST_GET_SOFTSKILLS';
export const RECEIVE_GET_SOFTSKILLS = 'RECEIVE_GET_SOFTSKILLS';
export const ERROR_GET_SOFTSKILLS = 'ERROR_GET_SOFTSKILLS';

export const REQUEST_GET_SOFTSKILL = 'REQUEST_GET_SOFTSKILL';
export const RECEIVE_GET_SOFTSKILL = 'RECEIVE_GET_SOFTSKILL';
export const ERROR_GET_SOFTSKILL = 'ERROR_GET_SOFTSKILL';

export const REQUEST_ADD_NEW_SOFTSKILL = 'REQUEST_ADD_NEW_SOFTSKILL';
export const RECEIVE_ADD_NEW_SOFTSKILL = 'RECEIVE_ADD_NEW_SOFTSKILL';
export const ERROR_ADD_NEW_SOFTSKILL = 'ERROR_ADD_NEW_SOFTSKILL';

export const REQUEST_EDIT_SOFTSKILL = 'REQUEST_EDIT_SOFTSKILL';
export const RECEIVE_EDIT_SOFTSKILL = 'RECEIVE_EDIT_SOFTSKILL';
export const ERROR_EDIT_SOFTSKILL = 'ERROR_EDIT_SOFTSKILL';

export const REQUEST_REMOVE_SOFTSKILL = 'REQUEST_REMOVE_SOFTSKILL';
export const RECEIVE_REMOVE_SOFTSKILL = 'RECEIVE_REMOVE_SOFTSKILL';
export const ERROR_REMOVE_SOFTSKILL = 'ERROR_REMOVE_SOFTSKILL';

export const TOGGLE_LOADING_SOFTSKILLS = 'TOGGLE_LOADING_SOFTSKILLS';

export const TOGGLE_SNACKBAR_SOFTSKILLS = 'TOGGLE_SNACKBAR_SOFTSKILLS';
export const TOGGLE_DELETE_SOFTSKILL_MODAL = 'TOGGLE_DELETE_SOFTSKILL_MODAL';
