export const REQUEST_GET_SEARCHREQUESTS = 'REQUEST_GET_SEARCHREQUESTS';
export const RECEIVE_GET_SEARCHREQUESTS = 'RECEIVE_GET_SEARCHREQUESTS';
export const ERROR_GET_SEARCHREQUESTS = 'ERROR_GET_SEARCHREQUESTS';

export const REQUEST_GET_SEARCHREQUEST = 'REQUEST_GET_SEARCHREQUEST';
export const RECEIVE_GET_SEARCHREQUEST = 'RECEIVE_GET_SEARCHREQUEST';
export const ERROR_GET_SEARCHREQUEST = 'ERROR_GET_SEARCHREQUEST';

export const REQUEST_ADD_NEW_SEARCHREQUEST = 'REQUEST_ADD_NEW_SEARCHREQUEST';
export const RECEIVE_ADD_NEW_SEARCHREQUEST = 'RECEIVE_ADD_NEW_SEARCHREQUEST';
export const ERROR_ADD_NEW_SEARCHREQUEST = 'ERROR_ADD_NEW_SEARCHREQUEST';

export const REQUEST_EDIT_SEARCHREQUEST = 'REQUEST_EDIT_SEARCHREQUEST';
export const RECEIVE_EDIT_SEARCHREQUEST = 'RECEIVE_EDIT_SEARCHREQUEST';
export const ERROR_EDIT_SEARCHREQUEST = 'ERROR_EDIT_SEARCHREQUEST';

export const REQUEST_REMOVE_SEARCHREQUEST = 'REQUEST_REMOVE_SEARCHREQUEST';
export const RECEIVE_REMOVE_SEARCHREQUEST = 'RECEIVE_REMOVE_SEARCHREQUEST';
export const ERROR_REMOVE_SEARCHREQUEST = 'ERROR_REMOVE_SEARCHREQUEST';

export const TOGGLE_LOADING_SEARCHREQUESTS = 'TOGGLE_LOADING_SEARCHREQUESTS';

export const TOGGLE_SNACKBAR_SEARCHREQUESTS = 'TOGGLE_SNACKBAR_SEARCHREQUESTS';
export const TOGGLE_DELETE_SEARCHREQUEST_MODAL = 'TOGGLE_DELETE_SEARCHREQUEST_MODAL';
